# -*- coding:utf-8 -*-
# doc2pdf.py: python script to convert doc to pdf with bookmarks!
# Requires Office 2007 SP2
# Requires python for win32 extension

'''
批量把WORD文件生成PDF文件
参考:http://blog.csdn.net/rumswell/article/details/7434302
'''
from win32com.client import Dispatch, constants, gencache
import os
import win32ui
import configparser

# Word转换为PDF
def word2pdf(filename):
    input = filename + '.docx'
    output = filename + '.pdf'
    pdf_name = output

    # 判断文件是否存在
    os.chdir(REPORT_DOC_PATH)
    if not os.path.isfile(input):
        print('%s not exist' % input)
        return False
    # 文档路径需要为绝对路径，因为Word启动后当前路径不是调用脚本时的当前路径。
    if (not os.path.isabs(input)):  # 判断是否为绝对路径
        # os.chdir(REPORT_DOC_PATH)
        input = os.path.abspath(input)  # 返回绝对路径
    else:
        print('%s not absolute path' % input)
        return False

    if (not os.path.isabs(output)):
        os.chdir(REPORT_PDF_PATH)
        output = os.path.abspath(output)
    else:
        print('%s not absolute path' % output)
        return False

    try:
        # enable python COM support for Word 2007
        # this is generated by: makepy.py -i "Microsoft Word 12.0 Object Library"
        gencache.EnsureModule('{00020905-0000-0000-C000-000000000046}', 0, 8, 4)
        # 开始转换
        w = Dispatch("Word.Application")
        try:
            doc = w.Documents.Open(input, ReadOnly=1)
            doc.ExportAsFixedFormat(output, constants.wdExportFormatPDF,
                                    Item=constants.wdExportDocumentWithMarkup,
                                    CreateBookmarks=constants.wdExportCreateHeadingBookmarks)
        except:
            print('文件打开不成功:',input)
        finally:
            w.Quit(constants.wdDoNotSaveChanges)

        if os.path.isfile(pdf_name):
            print('translate success:', os.path.abspath(pdf_name))
            return True
        else:
            print('translate fail')
            return False
    except:
        print('Word.Application启动不成功')
        return -1

def select_path(currentPath):
    '''
    通过使用对话窗口选择文件确定目录
    :return: 选择的路径名
    '''

    #设置起始路径,如果目标路径不存在，则选择当前路径
    if os.path.isdir(currentPath):
        os.chdir(currentPath)
    else:
        print('目录不存在:',currentPath)
        currentPath = os.getcwd()

    print("当前目录：%s"%(currentPath))

    dlg = win32ui.CreateFileDialog(1)  # 1表示打开文件对话框
    dlg.SetOFNInitialDir(currentPath)  # 设置打开文件对话框中的初始显示目录
    flag = dlg.DoModal()
    if flag == 2:
        print("未选择文件，程序退出")
        exit(1)

    filename = dlg.GetPathName()  # 获取选择的文件名称
    dlg.GetPathName()

    strSelectPath = os.path.dirname(filename)
    os.chdir(strSelectPath)

    currentPath = os.getcwd()
    print("当前目录：{}".format(currentPath))
    return currentPath

if __name__ == '__main__':

    #从配置文件中记取设置信息
    if os.path.isfile('path.ini'):#判断文件是否存在
        #从文件中读取配置信息
        config = configparser.ConfigParser()
        try:
            config.read('path.ini')
            currentPath = config['Path']['Target']
            Select = config['Path']['Select']
            FileName = config['File']['Name']
        except NameError as e:
            print('配置信息未定义:', e)
        except Exception as e:
            print('错误信息:', e)
    else:
        print('path.ini不存在')

    # 设置需要处理的目录

    if os.path.isdir(currentPath):
        os.chdir(currentPath)
    else:
        # 使用对话框选择路径
        currentPath = select_path(currentPath)
        # 不再需要重新选择路径
        Select = 0

    if Select == 1 or Select == 'Y' or Select == 'y':
        # 使用对话框选择路径
        currentPath = select_path(currentPath)

    currentPath = os.getcwd()
    print("当前目录：%s" % (currentPath))

    REPORT_DOC_PATH = currentPath
    REPORT_PDF_PATH = REPORT_DOC_PATH + '\pdf'

    if not os.path.exists(REPORT_PDF_PATH):
        os.mkdir(REPORT_PDF_PATH)
        print('目录已创建：', REPORT_PDF_PATH)

    # 转换成PDF文件
    for dirpath, dirnames, filenames in os.walk(REPORT_DOC_PATH):
        for file in filenames:
            #只转换后缀名为“.docx”的文件
            if os.path.splitext(file)[1]=='.docx':
                #转换成PDF文件
                rc = word2pdf(file.rstrip('.docx'))

    exit(0)
